### PR TITLE
Test/initial testing

### PR DESCRIPTION
**Pull request by freefony**

### CODE REVIEW

**Comment by janetbutts** [comment]
@jofomah , please review

**Comment by jofomah** [comment]
@janetbutts there is more like a draft without any implementation.

**Comment by janetbutts** [comment]
so @jofomah , should this get closed?

**Comment by jofomah** [comment]
@freefony i don't know what exactly this is supposed to do, if it is just an initial repo setup then maybe you need to make sure the test runner is set up probably, right now, i cant tell if the test runs or not

**Comment by freefony** [comment]
close this updates have been made in newer PRs

**Comment by janetbutts** [comment]
@freefony , do you need to close this request. if so, please do so,

**Pull request closed without merging**
