### PR TITLE
Feat/setup config

### PR DESCRIPTION
**Pull request by freefony**

### CODE REVIEW

**Comment by janetbutts** [comment]
@jofomah , please review

**Comment by freefony** [comment]
task added. you can also `jasmine-node spec`

**Comment by janetbutts** [comment]
@jofomah , please review again.

**Comment by jofomah** [comment]
@freefony please, add jasmine-node to package.json had to install it separately, also the tests didn't pass when i ran it. Got this:

``` Javascript

Failures:

  1) msges msges.type should be an object
   Message:
     Expected undefined to be <jasmine.any(function Object() { [native code] })>.
   Stacktrace:
     Error: Expected undefined to be <jasmine.any(function Object() { [native code] })>.
    at null.<anonymous> (/home/jofomah/sw-projects/sms-dispatcher/spec/msges-spec.js:13:26)

  2) msges msges.type should have properties
   Message:
     Expected false to be true.
   Stacktrace:
     Error: Expected false to be true.
    at null.<anonymous> (/home/jofomah/sw-projects/sms-dispatcher/spec/msges-spec.js:16:52)

  3) msges msges.type should have properties
   Message:
     Expected false to be true.
   Stacktrace:
     Error: Expected false to be true.
    at null.<anonymous> (/home/jofomah/sw-projects/sms-dispatcher/spec/msges-spec.js:17:48)

  4) recipients recipients.level should be an object
   Message:
     Expected undefined to equal <jasmine.any(function Object() { [native code] })>.
   Stacktrace:
     Error: Expected undefined to equal <jasmine.any(function Object() { [native code] })>.
    at null.<anonymous> (/home/jofomah/sw-projects/sms-dispatcher/spec/recipients-spec.js:14:33)

  5) recipients recipients.level should have at least one property
   Message:
     TypeError: Cannot call method 'indexOf' of undefined
   Stacktrace:
     TypeError: Cannot call method 'indexOf' of undefined
    at null.<anonymous> (/home/jofomah/sw-projects/sms-dispatcher/spec/recipients-spec.js:17:33)

  6) recipients recipients.bubble should return one of the elements of recipient.levels
   Message:
     TypeError: Cannot call method 'indexOf' of undefined
   Stacktrace:
     TypeError: Cannot call method 'indexOf' of undefined
    at null.<anonymous> (/home/jofomah/sw-projects/sms-dispatcher/spec/recipients-spec.js:36:33
```

**Comment by freefony** [comment]
Yes i will add it to package.json, but i am trying to do TDD so am writing
tests before adding features so those test should fail.

**Comment by jofomah** [comment]
well, i can't merge failing test without implementation in. let me know when you are done with the PR. btw the jasmine-node thing was missing in this PR package.json even with TDD it needs to be added.

**Comment by janetbutts** [comment]
@freefony , what is the status of this request?

**Comment by janetbutts** [comment]
@freefony , status please?

**Comment by freefony** [comment]
please close

**Comment by janetbutts** [comment]
new pull request. closing this one

**Pull request closed without merging**
